version: '3.8'

services:
  flask:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"

  nginx:
    container_name: nginx_server
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cgi-bin:/usr/share/nginx/html/cgi-bin
      - ./frontend/:/usr/share/nginx/html
    depends_on:
      - flask
